version: '2'
services:
  elastic:
    image: elasticsearch:5.0.0
    ports:
    - "9200:9200"
    - "9300-9300"
  rabbit:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
    - "5672:5672"
    - "5671:5671"
  cassandra:
    image: cassandra:3.9
    ports:
    - "9042:9042"
